version: '3.8'

services:
  api:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - PING_LISTEN_PORT=8080
    networks:
      - api_network
    deploy:
      replicas: 4
      placement:
        constraints:
          - node.role == worker

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - api_network

networks:
  api_network:
