version: '3.8'

services:
  # Service WordPress
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

  # Service MySQL
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend

  # Service Redis (cache)
  redis:
    image: redis:latest
    networks:
      - backend

  # Service Nginx (reverse proxy)
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - wordpress
    networks:
      - frontend

networks:
  frontend:
  backend:
